version: 1.3.2.{build}
branches:
  only:
  - master
assembly_info:
  patch: true
  file: '**\*AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: src\CalendarSyncPlus\CalendarSyncPlus.Installer\CalendarSyncPlus.Installer.wixproj
  verbosity: detailed
