version: 1.3.2.{build}
branches:
  only:
  - master
assembly_info:
  patch: true
  file: '**\*AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore src\CalendarSyncPlus\CalendarSyncPlus.sln
build:
  project: src\CalendarSyncPlus\CalendarSyncPlus.Installer\CalendarSyncPlus.Installer.wixproj
  verbosity: detailed
artifacts:
- path: src\CalendarSyncPlus\CalendarSyncPlus.Installer\bin\Release\CalendarSyncPlus.msi
  name: Installer
